### PR TITLE
 Streamline both message window and settings widget.

### PR DESCRIPTION
**Pull request by slgoldberg**
Here are my changes (including the Xcode project clean-up, which I had no way to remove really) -- primarily focused on solving bug #122 but also aimed at improving usability and greatly reducing extraneous widget- and window-creations in LT.

Here's a summary of the changes, but the code is hopefully quite clear:

RELEVANT CHANGES:
* Rework message window and settings UI widget hierarchy to only be created once per session.
* Add commandref for CR_SETTINGS_TOGGLE for binding to key or joystick button.
* Make Settings menu into a stateful toggle (i.e. checked/unchecked states).
* Add padding around text in message window, and margin on right edge; also tighten box slightly.
* Possible bug fixes (and definite performance and usability improvements):
  - Replace XPLMDrawTranslucentRectangle() with simple openGL code to do the same.
  - Reduce frequency and number of window *and* widget create/destroy cycles from O(1000) per session (XPluginStart to XPluginStop) to literally *2* (one for each) = O(1).
* Fix minor typos in two random comments.
* Generalize Xcode project (unavoidable inclusion in pull request); but should work (just fill in 2-3 custom build setting paths).

### CODE REVIEW

**Comment by slgoldberg** [comment]
Thanks -- and yes, I found one other mistake in my refactor (rename) of `DestroyWindow` to `RemoveWindow`. In `XPluginStop()` I mistakenly changed `DestroyWindow()` to `RemoveWindow()`, so I'll change that back.

Will do the other changes, in a bit, thanks.

**Comment by slgoldberg** [comment]
All the other fixes are in.

Except for your last comment which of course is the most important.

I looked through the code and I can't find a reason why any call from outside TextIO would need to use DestroyWindow.

Are you talking about macros like LOG_MSG, LOG_ALERT, etc.?  I'm missing your point.  I understand the bug and that we must check for failures, and I will add a failure check in DisplayMsgWindow() .. but what else would be needed?  Can you give me one example just so I'm clear?

I will send an updated request in a few minutes without that change, so we have the same basis. I just woke up an hour ago, sorry. It sucks we're so far apart time-wise.

  Steve

Thanks.

  Steve

**Comment by slgoldberg** [comment]
By the way -- two points about the bug in RemoveWindow():

1. The bug wasn't actually causing a resource leak as you stated. It simply undid my main objective (so that was bad, yes!) by forcing it to do as you had previously done -- i.e., re-creating the window each time (as it was before). So the latest change fixes that, yes.

2. However (!!) this strongly indicates that -- assuming my other changes did address the texture graphics bug as my full day of testing yesterday showed me it may -- it's **very** likely that `XPLMDrawTranslucentDarkBox` is the culprit!

Now I just have to figure out how to formulate that information into a useful bug report for LR.

  Steve

**Comment by slgoldberg** [comment]
Lots of comments. I'll reply to them all, thanks. I just need about 30-45 minutes so I hope you're still awake so I can get answers and go make changes tonight.

But three quick answers now:

(1) For the mkdir script question: I absolutely did NOT want you to see that. I that it was removed; I even went and looked for it before thinking I should remove it but didn't see it for some reason. That was an early attempt which I later didn't need. I'll try to answer better the rest soon.

(2) I *did* originally move the `g_window = NULL;` to the `DestroyWindow()` impl. But I for some reason decided it wasn't needed. You're entirely correct, of course, I'll add it back.

(3) Re: `settingsUI.Center()` above: I definitely meant *exactly* that by my comment about VR .. or did I forget to include the comment? (An inline comment in the code, I mean.)  I'll try to address it in my next pass. I underrstand; but I also think it's criminal to always force the window somewhere when users can move the window. So, now that it hides/shows instead of destroying/re-creating, I think it should be fixed. I can make it better, I just didn't want to write a ton of code here. I'll move the "toggle" into the settingsUI widget if that's okay... that will make it less ugly.

Stand by please, thanks.

  Steve

**Comment by TwinFan** [comment]
> So, now that it hides/shows instead of destroying/re-creating, I think it should be fixed.

The settings window was never destroyed before. The message window was, but not the settings. You didn't change the way the settings window is created. All windows move internally when switching to VR, that's why `Center` is in.

**Comment by slgoldberg** [comment]
>>The bug wasn't actually causing a resource leak

> Creating windows over and over again without a chance to destroy them because the window handle is NULLed before a call to Destroy is what I call a resource leak. Never mind...it's (nearly, see last line here) fixed.

Yes, correct, sorry.

>I am a bit reluctant to include OpenGL code when there is an XP API function available. And this is because XP is going to ditch OpenGL for Vulcan.

1. I completely understand, however if the bug as I suspect *is* in their implementation in XPLM, we have two choices:
  a. prove it is a bug, file it, then wait forever for them to find and fix it; or
  b. work around it and gather more evidence from user reports before making a more-convincing bug report (if at all).
I would opt for b. If I'm wrong (which I agree I may well be!) then the only risk is covered in my point 3 below.

2. I would truly be *shocked* if XPLM didn't support some kind of translation layer (or perhaps Vulkan does itself) e.g. with a drop-in library replacement for the basic openGL methods and a mapping to the new Vulkan equivalents under the covers. Or simpler yet, they'll likely always continue to have an openGL layer they let you use as before, then plop over top or something. (Since my code only works on a single 2D layer and uses the most basic of openGL methods.)

3. At some point, if X-Plane stops allowing XPLM users to use openGL, it will break many, many legacy plugins. So, users will be told they need to upgrade to the new, qualified versions of their plugins (that use Vulkan, presumably). It will be readily understood that LiveTraffic users will then need to update to get the compatible version. I don't think the risk of switching the preprocessor flag on at that point will be very high. That's why I left it as a flag.
Also, if they do stop supporting openGL, they'll surely have fixed the XPLM transparent-box drawing bug by then anyway (if there is one).

I am humble enough to admit I am only partly convinced there is an actual bug in `XPLMDrawTransparentDarkBox()` -- I may well be wrong. But that's okay, I think my proposed changes are still useful and safe.

 >I am actually thinking about how to remove all the OpenGL stuff and wouldn't like to introduce new OpenGL code. So I would indeed ask you to confirm that the texture mishaps are only gone with your OpenGL code in and cross-check that against a version with proper hide/show code but with the standard XP API call in.

See 1(a) above. I think it would be a difficult scenario to prove it, when there is another benefit here: I made the background color a little better for in-cockpit and against-sky viewing. The built-in box is a little too transparent.

But -- that said, to be honest, I was hoping *you* would do that testing. I just wanted to demonstrate the workaround to you, not necessarily become a full-time contributor to LiveTraffic, as much as I love it. :-)  I am running down the clock on my sabbatical, in which I wanted to work on ABC refactoring to use non-AI aircraft -- that to me is going to take precedence at this point. I can still try to do it, on my spare time, but if it blocks you adopting my changes, so be it.

Also, per above, I feel we do better to get feedback from real users on this, since I may not have enough ways to vary my environment to truly find and fix the texture glitch bug. I am just trying to move the needle here.

>(But indeed...just creating/destroying windows doesn't do anything to actual drawing. The drawing is done per frame and still is done, no matter if the window gets re-created or not.

Yes, absolutely -- I never claimed that was the reason. I was saying there may be *two* underlying causes that are playing together to trigger the bug.  It's just a theory.  But it could have something to do with a timing but in the open/close window code deep in XPLM or X-Plane, that gets tickled each time you *either* draw a transparent box (which yes -- is every draw cycle, I understand) or when you open/close a window.

Alternatively, perhaps the bug is in caching-for-performance code inside X-Plane when you draw a transparent box the very first time within a new window (i.e., on cache miss they incorrectly do something goofy). I'm just saying, who knows. I just know it's possible the more we do, and the more windows we open/close, the worse it seems to me anecdotally.

>I'm glad you did not actually change the way the settings UI gets created as this window was and is created only once and thereafter only shown/hidden.

Correct. I'm sorry bug it's *really* hard to fit the real meaning into a small short text window. And given your propensity for skipping long-winded text, I didn't feel it was worth the worry to clarify it there. I agree with your comment 100% percent. Your code already did the right thing (but not for the other window). I just changed it to show/hide which you also already supported.

In fact, in the end, for the widget stuff, my only proposed value-add is to add Toggle().

 >    I see in the file differences that all 3 third party libs (curl, png, XP API) are mentioned twice in some Children listing. That looks fishy.

I'm honestly not sure why anymore. I made those changes in the first set, before I really understood Xcode *or* LiveTraffic.  I was just trying to get it to build.  I never went back and scoured it to make sure there wasn't something wrong.  However, I *have* cloned my project with these changes on a fresh Xcode project *several* times without any problems. So, I guess whatever I did worked? :-)

But I'm not wedded to the specific changes. I just remember when I first tried to build it, all those things failed, and I believe you had hardcoded the exact paths to each dependent library in the configuration dialog that uses plaintext input with no assistance. So to re-add them, I would have had to delete all yours, then add my own manually. And each person would have to do that.

I actually wrote a README on all those changes but I don't think it was somehow committed. I can look. Either way, I was trying to centralize all new-developer startup to the three or four variables defined in the top-level configuration settings, and not make them worry about the rest.

>I don't see why the mkdir script is necessary.

Yes, that's bogus, please ignore the script. I'll delete it in my version. It's not used at all.

>I don't understand and probably don't like that the third party libraries are (also?) included via OTHER_LDFLAGS. XCode should take care of that itself and make it right. Maybe this caused the double-mention in the Children?

See my comments just above.. I think I addressed this same thing there.

>And I don't know what the two new files debug.xcscheme and release.xcscheme are about.

Ah -- this I *do* feel confident about and am excited to show you! :-)  The two schemes (debug.xcscheme and release.xcscheme) make it so Xcode presents them in the widget that is normally present at the top of the window (just below the menu bar).  That widget in my version says "[Release] => My Mac".  If you click on [Release], it shows you there are two schemes, and you can change it to say [Debug] instead, and now you're in Debug mode (so your builds will build the debug version, etc.).

Make sense?  It's just a fast, easy way to switch between the two modes (debug and build) -- apparently the standard way to do it in Xcode. And if you did have other configuration changes (that aren't already represented by the main configuration section) between the two, they are changeable in the Xcode "edit scheme" dialog; but I don't think there is anything else different for a library. All the real changes between the two are in the main config section.  This is just allowing you to quickly choose which to use for the next build.

If it's unclear, I can send a screenshot.

 >Maybe I just copy the good idea of introducing build-time macros to cover framework and install directories.

That would be great, thanks -- but please consider the two (shared) Xcode schemes.

>As to your question to my third comment and reasons why this is still a "Request changes" comment:
What I mean is that all calls to DestroyWindow, which are not done in TextIO.h/.cpp, need to stay DestroyWindow-calls. Please search
void RemoveWindow();
from TextIO.h and you'll see which calls I mean.

OK, I will do. Understood now. You want those changed back to DestroyWindow().

>All these calls are done from XPluginStart and XPluginStop and make sure resources get cleaned up properly in case the plugin cannot initialise properly (all calls to DestroyWindow are in the failure branches of if statements, and it is important to cleanup the window properly as otherwise issue #50 reoccurs) or during shutdown (which you apparently found out yourself).

Got it. Thanks.

>When handling MENU_ID_TOGGLE_SETTINGS I had put in the call to settingsUI.Center() deliberately. It became necessary in complex multi-monitor setups and jumps between VR and non-VR. Otherwise the settings window could move to a position where there is no monitor. Center()makes sure the settings window is visible and hence must stay in. This will simplify the code after MENU_ID_TOGGLE_SETTINGS.

Let me make extra sure I understand:  There are two cases:
1. After creating/centering the window initially in non-VR mode, the user changes to VR mode subsequently to that. Because they may be looking elsewhere, it is important to re-center the window that first time -- otherwise it will be confusing and not what the user wants.
2. Every time the user opens settings while in VR mode -- regardless of whether it was created and later moved to a better place for the user in 3-space -- they may come back later and find the window in a bad place, and thus expect it to always appear in the center of their view again, each time.

If I were a VR user, unless 2 is a real problem (I just don't know, sorry) then I would be much happier to be able to place the settings in a spot -- leave it (close it) -- and then have it re-open in that same spot later.  For that case, if we really need a reset/recenter, I could add that. (Recenter on demand, as a separate commandref.)

But if case 2 is really the big one, then for now, I would still hate to make the experience for non-VR users sucky if we can avoid it. So, in that case, can't I just force a re-center whenever VR is on?

Either way, I think moving this logic into a custom Toggle() method is ideal, because it makes the menu handling code flow the same way for everything, basically.

>In void DestroyWindow() the line g_window = NULL; is missing. I had asked to move the line there.

Addressed in previous message, but I put it back.

Will update the PR in several hours' time. If you reply before, great. :-)

Thanks.

**Comment by slgoldberg** [comment]
>And no hurry, please, but quality and testing. I won't pull in the next few days anyway.

I'm in no hurry. I simply am trying to manage my time, since I am quadruple-tasking and we are 9 timezones apart. :-( So, we only have 5 or so hours of time overlap.

So any comments I make about times, only have to do with trying to economize our interactions. Nothing to do with pushing to have you merge my changes in!  I'm totally fine with you talking as long as you like -- and I won't be offended if you take nothing! :-)

To be clear: I have no problem whatsoever with you leaving this in "Changes requested" mode! I truly appreciate your willingness to look at the changes and give feedback. I take no offense at any of it.  My biggest aspiration was simply to use this as a tool to communicate ideas to you, so even if you don't take the changes, at least this toolset makes it easy for me to make sure you know what I'm saying. :-)

Though I might ask if you can possibly clone my latest changes (after I make the next set) and try to build it on Windows and Linux, since I haven't tested there at all. I would also love to get the Windows build back from you because after two hours of struggling, I still could not get LT to build on Windows. :-( It's just so painful dealing with MS Visual Studio. :-(

Thanks.

  Steve

**Comment by slgoldberg** [comment]
Minor addendum to my comment about the "center" issue in my second-to-last message above:

I forgot to mention that in my changes, I was planning to handle a third scenario:
3. Users in non-VR mode resize their screen size or move things dynamically (e.g. by changing their monitor resolution, etc.) and the window may disappear if it's not rendered in the center each time. There would be no way for them to find and re-center the window.

I would probably say normally that this is another argument for a second commandref to "re-center" the settings window. But I believe it is a hard sell to normal users that they should have to go find it in the keyboard or joystick settings, etc.  Especially if in the moment they're confused where it went.

So I have a better idea, which I do in ABC as well:  simply "audit" the window positions each time in the draw-callback, and force the window into the visible screen area if it's outside.  This is a nuanced thing that I think I've finally mastered, but we'll see. :-)  The cool thing is I believe it's only a few lines of add'l code. I hope. :-)

Let me try it, and you can decide if you like it.

**Comment by slgoldberg** [comment]
Just FYI, I lost my window to work on this for the last day and a half, but I'll hopefully have some time to spend some getting the other changes in by the time you wake up Monday; else I'll let you know. If you have any other thoughts before then, feel free to let me know. Thanks.

  Steve

**Comment by slgoldberg** [comment]
OK, I just finished spending some time implementing the idea I mentioned above to resolve the centering issue.  I opted to do it in `TFWidget`.  I know it's risky -- I hope you see what I'm trying to do, and agree it's okay there. Those changes are coming in a second.

As mentioned, I added the `TFWidget::Toggle()` method to do the obvious thing.

Then I modified `TFWidget::Show()` in two ways:

1. I added a new virtual method `TFWidget::AuditWindowGeometry()` to reposition the widget (only if called on a root widget) if possible, either:
  a. by centering it, if it "needs" centering (which is always true for VR mode and first time through); or
  b. by moving it back on-screen if something changed in the screen size/position that might cause the window to fall off into a non-visible area (including OS windows, regular windows, and modern windows).

2. I modified `TFWidget::Show()` to call the new `AuditWindowGeometry()` above when showing a root-level widget (whether new or previously hidden).  There were several ways to do that; let me know if you have a better way.

I noticed a couple of places I wasn't sure whether *every* widget would hit this code, or only ever the root widget. (You do call `XPLMSetWindowIsVisible()` in that spot, so I guess it's only root widgets?  Or do you force the window shown even if the caller just calls `Show(true)` on a specific sub-widget? I'm just wondering if I did it right or if that check isn't even needed.

I also fixed the missing "`g_window = 0`" in the last commit.

And in the previous commit I fixed the other comment about clean-up on failure, as well as fixing the tabs setting for Xcode (pretty straightforward) to keep it how you like it.

So let me know where we stand if you get a chance.

Thanks.

  Steve

**Comment by slgoldberg** [comment]
Sometimes I don't understand what Xcode is thinking. I explictly unchecked README.md because it's nowhere near ready, but for some reason it chose to commit that file as well this last time. Argh, sorry, please ignore it. Would you prefer I push again with my changes reverted?

**Comment by TwinFan** [comment]
I think you should give it a break here. You are solving simple things the complex way. I believe that good code is not code you can't add to, but where you can't take away from. I solved the problem with a simple call to "Center()" and I will not pull your complex change in a root class of an entire widget hierarchy. BTW...`TFMainWindowWidget` implements main windows.

So, please, do me and yourself a favor and just leave this pull request where it is. I will cherry-pick the stuff around hiding the message are window, because that adds value. Given the multitudes of changes now I might even decide to implement it quickly myself.

**Comment by slgoldberg** [comment]
OK sounds good, thanks.

**Comment by slgoldberg** [comment]
Oh, and I *did* try to start with `TFMainWindowWidget` -- but it was so basic, it almost seemed to serve no purpose. I couldn't find docs for it (was I missing something?) and when I followed the logic, most of the actual XPLM window references (such as showing the XPLM window for a widget hierarchy) seemed to be done in the base TFWidget class.

I figured, if I put the code in the main window widget, you'd berate me saying that window was only to be used as the meta-window to contain all widgets, not as a visible window.  I thought about asking you, but then I figured, I'd just write the code and you could tellme if I should move it -- which I was happy to have you tell me,.. but to have you tell me it's over-complicated is.. well, not useful.

Also, I don't agree that what's in the last set of changes is complex code or a complex solution at all.  If anything, you made it complex by making me revisit how it all worked instead of just taking what I did and fixing it up how you wanted which is how I thought it would go last week.

In the end, I found an elegant way to make it so users (end-users and users of the widget library) can't accidentally end up with widgets rooted on a window that disappears just because you change configurations. It's really quite simple what I did. I don't know what the heck you're talking about it being complicated.

Either way, I really want to know if this fixes the texture glitch bug. That was the goal, not to fundamentally build a flexible window management solution. (So I agree with you on that point.)

Take what you like, just let me know how I am supposed to do it if you're just going to cherrypick -- i.e., whether I somehow abandon/delete this stuff eventually or what. Thanks.

  Steve

**Comment by TwinFan** [comment]
I have now reconciled 2 changes (OpenGL drawing, and the idea of hiding instead of destroying the msg area) and committed it referring to issue #122, which it possibly fixes.

I am currently reluctant to pull the remainder of this request.

**Comment by slgoldberg** [comment]
Not a problem; we can either just leave it sitting for reference, or you
can close it and I might make a separate branch just to keep track of the
rest in case you ever want it. Thanks.

  Steve

**Comment by TwinFan** [comment]
See [above](https://github.com/TwinFan/LiveTraffic/pull/150#issuecomment-520611281): Will not pull the remainder of the changes.

**Pull request closed without merging**
